// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using xiaoPage.Data;

#nullable disable

namespace xiaoPage.Migrations
{
    [DbContext(typeof(ApplicationDb))]
    [Migration("20240217131135_AddActorTableToDb")]
    partial class AddActorTableToDb
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.27")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("xiaoPage.Model.Actor", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<int>("Birthday")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("ID");

                    b.ToTable("actors");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Birthday = 1990,
                            Name = "Action"
                        },
                        new
                        {
                            ID = 2,
                            Birthday = 2000,
                            Name = "history"
                        },
                        new
                        {
                            ID = 3,
                            Birthday = 1993,
                            Name = "but"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
